package main;

import controller.Controller;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

public class Dashboard extends javax.swing.JFrame {
    private final Controller controller;
    private AdicionaReceita adicionaReceita;
    private AdicionaDespesa adicionaDespesa;
    public Dashboard(Controller controller) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.controller = controller;
        
        
        
        chartPanel.setLayout(new BorderLayout());

        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Categoria A", 30.0);
        dataset.setValue("Categoria B", 40.0);
        dataset.setValue("Categoria C", 20.0);
        dataset.setValue("Categoria D", 10.0);
        
        JFreeChart chart = ChartFactory.createPieChart(
            "Gráfico de Pizza",  // Título do gráfico
            dataset,            // Conjunto de dados
            true,               // Inclui legenda
            true,
            false
        );
        
        ChartPanel chartPanelComponent = new ChartPanel(chart); // Usando um nome diferente para o componente do gráfico
        chartPanelComponent.setPreferredSize(new Dimension(400, 300));  // Define as dimensões do painel do gráfico
        chartPanel.add(chartPanelComponent, BorderLayout.CENTER);
        getContentPane().add(chartPanel);
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        btnAdicionaReceita = new javax.swing.JButton();
        btnAdicionaDespesa = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenuItem();
        menuRFixas = new javax.swing.JMenuItem();
        menuFixas = new javax.swing.JMenuItem();
        menuVariaveis = new javax.swing.JMenuItem();
        menuAdicionais = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel1.setText("Saldo Atual:");

        txtSaldo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtSaldo.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnAdicionaReceita.setText("Adicionar Receita");
        btnAdicionaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaReceitaActionPerformed(evt);
            }
        });

        btnAdicionaDespesa.setText("Adicionar Despesa");
        btnAdicionaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        menuPessoa.setText("Pessoa");
        menuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPessoa);

        menuRFixas.setText("Receitas Fixas");
        menuRFixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRFixasActionPerformed(evt);
            }
        });
        jMenu1.add(menuRFixas);

        menuFixas.setText("Despesas Fixas");
        menuFixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFixasActionPerformed(evt);
            }
        });
        jMenu1.add(menuFixas);

        menuVariaveis.setText("Despesas Variáveis");
        jMenu1.add(menuVariaveis);

        menuAdicionais.setText("Despesas Adicionais");
        jMenu1.add(menuAdicionais);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edição");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Excluir");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionaReceita)
                            .addComponent(btnAdicionaDespesa)))
                    .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(635, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionaReceita)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionaDespesa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaActionPerformed
        CadastroPessoa dashboard = new CadastroPessoa(controller);
        dashboard.setVisible(true);
    }//GEN-LAST:event_menuPessoaActionPerformed

    private void btnAdicionaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaReceitaActionPerformed
        adicionaReceita = new AdicionaReceita(controller);
        adicionaReceita.setVisible(true);
        adicionaReceita.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Fechou a janela AdicionaReceita");
                float saldo = controller.RetornaSaldo();
                Locale brasilLocale = new Locale("pt", "BR");
                DecimalFormat df = (DecimalFormat) DecimalFormat.getCurrencyInstance(brasilLocale);
                String valorFormatado = df.format(saldo);
                txtSaldo.setText(valorFormatado);
                if (saldo < 0) {
                    txtSaldo.setForeground(Color.RED); // Define a cor para vermelho se o saldo for negativo
                } else {
                    txtSaldo.setForeground(Color.BLUE); // Define a cor para azul se o saldo for positivo
                }
                DefaultPieDataset dataset = new DefaultPieDataset();
                
                String nomeReceita = controller.RetornaReceitaT();
                //System.out.println(nomeReceita);
                String[] receitas = nomeReceita.split("## ");
                
                    for (String receita : receitas) {
                        String[] partes = receita.split(", ");
                        System.out.println(nomeReceita);
                            if (partes.length >= 2) {
                                System.out.println("Aqui 2");
                                String nome = partes[0].trim(); // Remove espaços em branco
                                double valor = Double.parseDouble(partes[1].trim()); // Remove espaços em branco
                                System.out.println(nome + ", " + valor);
                                dataset.setValue(nome, valor);
                            }

                    }
        
                
                
                JFreeChart chart = ChartFactory.createPieChart(
                    "Suas Receitas",
                    dataset,
                    true,
                    true,
                    false
                );

                ChartPanel chartPanelComponent = new ChartPanel(chart);
                chartPanelComponent.setPreferredSize(new Dimension(400, 300));
                chartPanel.removeAll(); // Limpar o painel do gráfico
                chartPanel.add(chartPanelComponent, BorderLayout.CENTER);
                        }
        });
    }//GEN-LAST:event_btnAdicionaReceitaActionPerformed

    private void menuRFixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRFixasActionPerformed
        String receita = JOptionPane.showInputDialog("Informe o nome da Receita Fixa:");
        controller.CadastroReceita(receita, "A");
    }//GEN-LAST:event_menuRFixasActionPerformed

    private void btnAdicionaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaDespesaActionPerformed
        adicionaDespesa = new AdicionaDespesa(controller);
        adicionaDespesa.setVisible(true);
        adicionaDespesa.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Fechou a janela AdicionaDespesa");
                float saldo = controller.RetornaSaldo();
                Locale brasilLocale = new Locale("pt", "BR");
                DecimalFormat df = (DecimalFormat) DecimalFormat.getCurrencyInstance(brasilLocale);
                String valorFormatado = df.format(saldo);
                txtSaldo.setText(valorFormatado);
                if (saldo < 0) {
                    txtSaldo.setForeground(Color.RED); // Define a cor para vermelho se o saldo for negativo
                } else {
                    txtSaldo.setForeground(Color.BLUE); // Define a cor para azul se o saldo for positivo
                }
            }
        });
    }//GEN-LAST:event_btnAdicionaDespesaActionPerformed

    private void menuFixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFixasActionPerformed
        String despesa = JOptionPane.showInputDialog("Informe o nome da Despesa Fixa:");
        controller.CadastroDespesa(despesa, "A");
    }//GEN-LAST:event_menuFixasActionPerformed

    
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaDespesa;
    private javax.swing.JButton btnAdicionaReceita;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAdicionais;
    private javax.swing.JMenuItem menuFixas;
    private javax.swing.JMenuItem menuPessoa;
    private javax.swing.JMenuItem menuRFixas;
    private javax.swing.JMenuItem menuVariaveis;
    public javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables
}
